### ISSUE TITLE
Not sure what this is, but it's not the choripan I wanted

### ISSUE THREAD

**Issue by GuidoDipietro** [frankdilu/CheLang#6]
![image](https://user-images.githubusercontent.com/48221146/87601823-3e5afd80-c6cc-11ea-85d9-56f28714ed0f.png)
CheDevelopers, I found a thing.

Triggered by calling Campora() then hitting Ctrl+C once to halt the execution, then once again because the audio kept running on the background.

Probably has something to do with the ```playsound``` lib (which, from what I've found, is only able to play a track and not to stop it).

But _it's all right_. Don't worry. I know that tune is meant to be played for hours on end and not to be interrupted. _No te calentés_.

**Comment by francodilu** [comment]
Hey men, what's up? First of all read the readme again, i changed several things so now you can use spanish if you want.
The track still playing because you cant remove the kirchnerism easy...
About the error: Thanks! I did not realize that. I dont really know why, but sometimes happens and sometimes dont. Anyway, i fix several causes in the next release (today) :)
